grafana:
  enabled: true

prometheus: 
  enabled: true
  alertmanager:
    persistentVolume:
      enabled: false
  server:
    persistentVolume:
      enabled: false

loki:
  auth_enabled: false
  persistence:
    enabled: true
    storageClassName: nfs-client
    size: 5Gi

minio:
  enabled: true

gateway:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
    - host: dev-loki.rnawealth.com
      paths:
        - path: /
          pathType: ImplementationSpecific
